### ISSUE TITLE
combine helpers

### ISSUE THREAD

**Issue by krispy1298** [alexsomeoddpilot/sop-gulp-static#2]
how can i combine these helpers?

```
handlebars.registerHelper("everyOtherOffset", function (index, amount, offset, scope) {
    if (((++index) - offset) % amount ) {
      return scope.inverse(this);
    } else {
      return scope.fn(this);
    }
});

handlebars.registerHelper("everyOther", function (index, amount, scope) {
    if (++index % amount ) {
      return scope.inverse(this);
    } else {
      return scope.fn(this);
    }
});

```

ive tried 

```
if offset === undefined
```

but no dice

**Comment by alexsomeoddpilot** [comment]
Here’s my first, quick stab at it:

https://gist.github.com/alexsomeoddpilot/b64ea8333cb729b41b7d

Its untested, but gives you an idea of how you can solve it. Handlebars
helpers can take optional parameters via attribute like syntax.

On Thu, Jan 22, 2015 at 11:08 AM, krispy1298 <notifications@github.com>
wrote:

> how can i combine these helpers?
>
> handlebars.registerHelper("everyOtherOffset", function (index, amount, offset, scope) {
>     if (((++index) - offset) % amount ) {
>       return scope.inverse(this);
>     } else {
>       return scope.fn(this);
>     }
> });
>
> handlebars.registerHelper("everyOther", function (index, amount, scope) {
>     if (++index % amount ) {
>       return scope.inverse(this);
>     } else {
>       return scope.fn(this);
>     }
> });
>
>
> ive tried
>
> if offset === undefined
>
> but no dice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexsomeoddpilot/sop-gulp-static/issues/2>.
>



-- 

*Alex Robertson*
alex@someoddpilot.com

*Someoddpilot*
1539 N. Damen Ave. 2nd Floor
Chicago, IL 60622
Ph. (773) 529-7128
Fx. (877) 350-3750
http://www.someoddpilot.com
http://www.thispublicworks.com
