### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by krispy1298** [alexsomeoddpilot/sop-gulp-static#5]
handlebars doesnt address this

these seem decent
http://stackoverflow.com/questions/17934207/handlebars-js-custom-function-sort

which do you prefer? other thoughts?

**Comment by alexsomeoddpilot** [comment]
Sorting and pagination will be handled before data is handed off to Handlebars.

The view‘s responsibility is to simply display the data with minor transformations.

I'll address how to set options for sorting.

**Comment by alexsomeoddpilot** [comment]
The [collections helper](https://github.com/alexsomeoddpilot/gulp-collections) takes a `sortBy` option, which should be a function which compares the two items.
